language: ruby
install: npm install && bundle install --jobs=3 --retry=3
before_script:
  - psql -c 'create database upvote_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: npm test && bundle exec rails test
rvm:
  - 2.4.1
addons:
  postgresql: "9.6"
