export const CREATE_USER_SESSION_SUCCESS = 'CREATE_USER_SESSION_SUCCESS';
export const DESTROY_USER_SESSION = 'DESTROY_USER_SESSION';

export const GET_UPVOTES_SUCCESS = 'GET_UPVOTES_SUCCESS';
export const ARCHIVE_UPVOTES_SUCCESS = 'ARCHIVE_UPVOTES_SUCCESS';
